# Generated by Django 5.2 on 2025-05-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='latest_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]

