# Generated by Django 5.2 on 2025-05-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=10),
        ),
    ]
