# Generated by Django 5.2 on 2025-05-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_user_document_owner_alter_userprofile_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
