# Generated by Django 5.2 on 2025-05-13 04:58

import mainapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_tokenspackage_userprofile_tokens_card_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cardholder_name',
            field=models.CharField(default='one-off-value', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(max_length=4, validators=[mainapp.validators.validate_cvv]),
        ),
    ]
