# Generated by Django 5.2 on 2025-05-09 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_document_latest_update'),
        ('mainapp', '0002_message'),
    ]

    operations = [
    ]
