# Generated by Django 5.2 on 2025-05-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_card_cardholder_name_alter_card_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='package',
            field=models.CharField(default='dne', max_length=256),
            preserve_default=False,
        ),
    ]
